name: CI with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build_test.yml

  sonar_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/sonar.yml
